sudo: required
services:
  - docker

before_install:
  - docker build -t meiyenl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run meiyenl/react-test npm test -- --coverage

after_success:
  - docker build -t meiyenl/multi-client ./client
  - docker build -t meiyenl/multi-nginx ./nginx
  - docker build -t meiyenl/multi-server ./server
  - docker build -t meiyenl/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker tag meiyenl/multi-client meiyenl:multi-client
  - docker push meiyenl:multi-client
  - docker tag meiyenl/multi-nginx meiyenl:nginx
  - docker push meiyenl:multi-nginx
  - docker tag meiyenl/multi-server meiyenl:multi-server
  - docker push meiyenl:ulti-server
  - docker tag meiyenl/multi-worker meiyenl:multi-worker
  - docker push meiyenl:multi-worker

deploy:
  provider: elasticbeanstalk
  #region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: 
  bucket_path: docker-multi
  on:
    branch: master
  #access_key_id: $AWS_ACCESS_KEY
  #secret_access_key:
   # secure: $AWS_SECRET_KEY
